name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- python=3.10
- pip
- pip:
  - joblib==1.4.2
  - matplotlib==3.9.1
  - numpy==2.0.0
  - pandas==2.2.2
  - scikit-learn==1.5.1
  - xgboost==2.1.0