version: 1.2
workflows:
  - subclass: WDL
    enableAutoDois: false
    primaryDescriptorPath: /workflows/main.wdl
    readMePath: /README.md
    authors:
      - name: Zhou, Y., Maurya, A.K., Deng, Y., Fletcher, M.P., Ren, C., & Taylor, A.
        affiliation: Oxford-GSK Institute of Molecular and Computational Medicine, Nuffield Department of Medicine, University of Oxford, Old Road Campus, Oxford,OX3 7BN