# This script generates an interactive network plot with draggable nodes, allowing users to freely explore the network in an intuitive and flexible way.
# To run the script, use the command line: Rscript DraggableNetwork.R. Need to load previously stored R object after running the main workflow.
# This will produce an HTML file named "Interactive_PPI.html" that users can open in a web browser to explore the network through an interactive interface.

library(igraph)
library(visNetwork)
library(htmltools)

plotDraggable <- function(g, nodeName, nodeColor, nodeShape, nodeValue, myTitle){
  
  # Save colorbar legend to file
  png("color_legend.png",res = 300)
  
  # adjust margins
  par(mar = c(1, 0.01, 1, 0.01))  
  
  image.plot(legend.only = TRUE, 
             zlim = range(as.numeric(nodeValue[!is.na(nodeValue)])),
             col = myPalette_expanded(1000),
             horizontal = TRUE, 
             legend.width = 0.3, 
             legend.mar = 3,
             legend.args = list(text = myTitle, side = 1, font = 2, line = 0.5, cex = 0.3),
             axis.args = list(cex.axis = 0.3, tck = -0.8, mgp = c(3, 0.1, 0),
                              at = pretty(range(as.numeric(nodeValue), na.rm = TRUE)),
                              labels = format(pretty(range(as.numeric(nodeValue), na.rm = TRUE)), scientific = TRUE, digits = 2)
             ))
  
  # Create shape legend separately in the same image if needed
  legend(x = "bottom",                   
         inset = c(0, 0.4),                
         legend = c("High SHAP Protein", "Coexpressed Interactor"),
         pch = c(21, 22),            
         pt.bg = c("white", "white"),
         pt.cex = 0.4,
         cex = 0.3,
         text.font = 2,
         bty = "n",
         horiz = TRUE,
         seg.len = 0.2,
         xpd = TRUE)
  
  dev.off()
  
  nodes <- data.frame(
    id = V(g)$name,
    label = nodeName,
    color = nodeColor,
    shape = ifelse(nodeShape == "circle", "dot", "square"),  # visNetwork shape syntax
    size = 10,  # can customize based on SHAP value or other
    font = list(size = 15, face = "bold")  # bold label
  )
  
  # Create edge data frame
  edges <- as_data_frame(g, what = "edges")
  edges <- data.frame(
    from = edges$from,
    to = edges$to,
    color = "grey"
  )
  
  # Create interactive network
  network_plot <- visNetwork(nodes, edges, height = "1000px", width = "100%") %>%
    visNodes(font = list(size = 15, face = "bold"), shadow = TRUE) %>%
    visEdges(smooth = FALSE) %>%
    visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
    visLayout(randomSeed = 123) %>%
    visPhysics(stabilization = TRUE)
  
  # Create HTML-based shape legend and include the color bar image
  img_base64 <- base64enc::dataURI(file = "color_legend.png", mime = "image/png")
  
  # Use in HTML
  legend_add <- HTML(sprintf('
  <div style="text-align: center; margin-top: 0px;">
    <img src="%s" style="width: 50%%; margin-bottom: 0px;" />
  </div>
', img_base64))
  
  # Combine the visNetwork plot and legend into one HTML output
  combined_output <-browsable(
    tagList(
      network_plot,
      legend_add
    )
  )
  
  saveWidget(combined_output, file = "Interactive_PPI.html", selfcontained = TRUE)
  
}

### Load the saved object generated by protein_network.R for creating the interactive PPI plot
load("Object4InteractivePlot.rdat")

### Make the interactive plot
plotDraggable(g, nodeName2, nodeColor, "circle", nodeValue, myTitle)
plotDraggable(g_expanded, nodeName2_expanded, nodeColor_expanded, nodeShape, nodeValue_expanded, myTitle_expanded)
