name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- python
- joblib<=1.4.0
- matplotlib<=3.9.0
- numpy<=1.23.5
- optuna<=4.0.0
- pandas<=2.2.2
- scikit-learn<=1.5.1
- shap<=0.46.0
- pytorch::pytorch<=2.5.0