name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- python
- libtiff=4.0.*
- joblib<=1.4.0
- matplotlib<=3.9.0
- numpy<=1.23.5
- pandas<=2.2.2
- scikit-learn<=1.4.2
- xgboost<=2.1.0
- shap<=0.45.0
- pillow<=10.3.0
- tensorflow<=2.12.0
