name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - fpdf<=1.7.2
  - joblib<=1.4.2
  - lightgbm<=4.5.0
  - matplotlib<=3.9.1
  - numpy<=1.26.4
  - optuna<=4.0.0
  - pandas<=2.2.2
  - scikit-learn<=1.5.1
  - seaborn<=0.13.2
  - shap<=0.46.0
  - umap-learn<=0.5.6
  - xgboost<=2.1.1