name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - joblib<=1.4.2
  - matplotlib<=3.9.1
  - numpy<=1.26.4
  - pandas<=2.2.2
  - scikit-learn<=1.5.1
  - xgboost<=2.1.1
  - shap<=0.45.1
  - fpdf
  - seaborn
  - umap-learn